blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Reporting
    url: https://github.com/comarch/MarkQuire/security/advisories/new
    about: Privately report suspected security vulnerabilities.
